const BASE_URL = 'https://iptv-org.github.io/iptv';

const CATEGORY = {
  'Auto': '/categories/auto.m3u',
  'Animation': '/categories/animation.m3u',
  'Business': '/categories/business.m3u',
  'Classic': '/categories/classic.m3u',
  'Comedy': '/categories/comedy.m3u',
  'Cooking': '/categories/cooking.m3u',
  'Culture': '/categories/culture.m3u',
  'Documentary': '/categories/documentary.m3u',
  'Education': '/categories/education.m3u',
  'Entertainment': '/categories/entertainment.m3u',
  'Family': '/categories/family.m3u',
  'General': '/categories/general.m3u',
  'Kids': '/categories/kids.m3u',
  'Legislative': '/categories/legislative.m3u',
  'Lifestyle': '/categories/lifestyle.m3u',
  'Local': '/categories/local.m3u',
  'Movies': '/categories/movies.m3u',
  'Music': '/categories/music.m3u',
  'News': '/categories/news.m3u',
  'Outdoor': '/categories/outdoor.m3u',
  'Relax': '/categories/relax.m3u',
  'Religious': '/categories/religious.m3u',
  'Series': '/categories/series.m3u',
  'Science': '/categories/science.m3u',
  'Shop': '/categories/shop.m3u',
  'Sports': '/categories/sports.m3u',
  'Travel': '/categories/travel.m3u',
  'Weather': '/categories/weather.m3u',
};

const COUNTRY = {
  'Afghanistan': '/countries/af.m3u',
  'Albania': '/countries/al.m3u',
  'Algeria': '/countries/dz.m3u',
  'American Samoa': '/countries/as.m3u',
  'Andorra': '/countries/ad.m3u',
  'Angola': '/countries/ao.m3u',
  'Anguilla': '/countries/ai.m3u',
  'Antigua & Barbuda': '/countries/ag.m3u',
  'Argentina': '/countries/ar.m3u',
  'Armenia': '/countries/am.m3u',
  'Aruba': '/countries/aw.m3u',
  'Australia': '/countries/au.m3u',
  'Austria': '/countries/at.m3u',
  'Azerbaijan': '/countries/az.m3u',
  'Bahamas': '/countries/bs.m3u',
  'Bahrain': '/countries/bh.m3u',
  'Bangladesh': '/countries/bd.m3u',
  'Barbados': '/countries/bb.m3u',
  'Belarus': '/countries/by.m3u',
  'Belgium': '/countries/be.m3u',
  'Belize': '/countries/bz.m3u',
  'Benin': '/countries/bj.m3u',
  'Bermuda': '/countries/bm.m3u',
  'Bhutan': '/countries/bt.m3u',
  'Bolivia': '/countries/bo.m3u',
  'Bosnia': '/countries/ba.m3u',
  'Botswana': '/countries/bw.m3u',
  'Brazil': '/countries/br.m3u',
  'British Virgin Islands': '/countries/vg.m3u',
  'Brunei': '/countries/bn.m3u',
  'Bulgaria': '/countries/bg.m3u',
  'Burkina Faso': '/countries/bf.m3u',
  'Burundi': '/countries/bi.m3u',
  'Cambodia': '/countries/kh.m3u',
  'Cameroon': '/countries/cm.m3u',
  'Canada': '/countries/ca.m3u',
  'Cape Verde': '/countries/cv.m3u',
  'Cayman Islands': '/countries/ky.m3u',
  'Central African Republic': '/countries/cf.m3u',
  'Chad': '/countries/td.m3u',
  'Chile': '/countries/cl.m3u',
  'China': '/countries/cn.m3u',
  'Colombia': '/countries/co.m3u',
  'Comoros': '/countries/km.m3u',
  'Congo - Brazzaville': '/countries/cg.m3u',
  'Congo - Kinshasa': '/countries/cd.m3u',
  'Cook Islands': '/countries/ck.m3u',
  'Costa Rica': '/countries/cr.m3u',
  'Croatia': '/countries/hr.m3u',
  'Cuba': '/countries/cu.m3u',
  'Curaçao': '/countries/cw.m3u',
  'Cyprus': '/countries/cy.m3u',
  'Czechia': '/countries/cz.m3u',
  'Côte d’Ivoire': '/countries/ci.m3u',
  'Denmark': '/countries/dk.m3u',
  'Djibouti': '/countries/dj.m3u',
  'Dominica': '/countries/dm.m3u',
  'Dominican Republic': '/countries/do.m3u',
  'Ecuador': '/countries/ec.m3u',
  'Egypt': '/countries/eg.m3u',
  'El Salvador': '/countries/sv.m3u',
  'Equatorial Guinea': '/countries/gq.m3u',
  'Eritrea': '/countries/er.m3u',
  'Estonia': '/countries/ee.m3u',
  'Eswatini': '/countries/sz.m3u',
  'Ethiopia': '/countries/et.m3u',
  'Faroe Islands': '/countries/fo.m3u',
  'Fiji': '/countries/fj.m3u',
  'Finland': '/countries/fi.m3u',
  'France': '/countries/fr.m3u',
  'French Guiana': '/countries/gf.m3u',
  'French Polynesia': '/countries/pf.m3u',
  'French Southern Territories': '/countries/tf.m3u',
  'Gabon': '/countries/ga.m3u',
  'Gambia': '/countries/gm.m3u',
  'Georgia': '/countries/ge.m3u',
  'Germany': '/countries/de.m3u',
  'Ghana': '/countries/gh.m3u',
  'Greece': '/countries/gr.m3u',
  'Greenland': '/countries/gl.m3u',
  'Grenada': '/countries/gd.m3u',
  'Guadeloupe': '/countries/gp.m3u',
  'Guam': '/countries/gu.m3u',
  'Guatemala': '/countries/gt.m3u',
  'Guinea': '/countries/gn.m3u',
  'Guinea-Bissau': '/countries/gw.m3u',
  'Haiti': '/countries/ht.m3u',
  'Honduras': '/countries/hn.m3u',
  'Hong Kong': '/countries/hk.m3u',
  'Hungary': '/countries/hu.m3u',
  'Iceland': '/countries/is.m3u',
  'India': '/countries/in.m3u',
  'Indonesia': '/countries/id.m3u',
  'International': '/countries/int.m3u',
  'Iran': '/countries/ir.m3u',
  'Iraq': '/countries/iq.m3u',
  'Ireland': '/countries/ie.m3u',
  'Israel': '/countries/il.m3u',
  'Italy': '/countries/it.m3u',
  'Jamaica': '/countries/jm.m3u',
  'Japan': '/countries/jp.m3u',
  'Jordan': '/countries/jo.m3u',
  'Kazakhstan': '/countries/kz.m3u',
  'Kenya': '/countries/ke.m3u',
  'Kiribati': '/countries/ki.m3u',
  'Kosovo': '/countries/xk.m3u',
  'Kuwait': '/countries/kw.m3u',
  'Kyrgyzstan': '/countries/kg.m3u',
  'Laos': '/countries/la.m3u',
  'Latvia': '/countries/lv.m3u',
  'Lebanon': '/countries/lb.m3u',
  'Lesotho': '/countries/ls.m3u',
  'Liberia': '/countries/lr.m3u',
  'Libya': '/countries/ly.m3u',
  'Liechtenstein': '/countries/li.m3u',
  'Lithuania': '/countries/lt.m3u',
  'Luxembourg': '/countries/lu.m3u',
  'Macao': '/countries/mo.m3u',
  'Madagascar': '/countries/mg.m3u',
  'Malawi': '/countries/mw.m3u',
  'Malaysia': '/countries/my.m3u',
  'Maldives': '/countries/mv.m3u',
  'Mali': '/countries/ml.m3u',
  'Malta': '/countries/mt.m3u',
  'Marshall Islands': '/countries/mh.m3u',
  'Martinique': '/countries/mq.m3u',
  'Mauritania': '/countries/mr.m3u',
  'Mauritius': '/countries/mu.m3u',
  'Mayotte': '/countries/yt.m3u',
  'Mexico': '/countries/mx.m3u',
  'Micronesia': '/countries/fm.m3u',
  'Moldova': '/countries/md.m3u',
  'Monaco': '/countries/mc.m3u',
  'Mongolia': '/countries/mn.m3u',
  'Montenegro': '/countries/me.m3u',
  'Montserrat': '/countries/ms.m3u',
  'Morocco': '/countries/ma.m3u',
  'Mozambique': '/countries/mz.m3u',
  'Myanmar': '/countries/mm.m3u',
  'Namibia': '/countries/na.m3u',
  'Nauru': '/countries/nr.m3u',
  'Nepal': '/countries/np.m3u',
  'Netherlands': '/countries/nl.m3u',
  'New Caledonia': '/countries/nc.m3u',
  'New Zealand': '/countries/nz.m3u',
  'Nicaragua': '/countries/ni.m3u',
  'Niger': '/countries/ne.m3u',
  'Nigeria': '/countries/ng.m3u',
  'Niue': '/countries/nu.m3u',
  'Norfolk Island': '/countries/nf.m3u',
  'North Korea': '/countries/kp.m3u',
  'North Macedonia': '/countries/mk.m3u',
  'Northern Mariana Islands': '/countries/mp.m3u',
  'Norway': '/countries/no.m3u',
  'Oman': '/countries/om.m3u',
  'Pakistan': '/countries/pk.m3u',
  'Palau': '/countries/pw.m3u',
  'Palestine': '/countries/ps.m3u',
  'Panama': '/countries/pa.m3u',
  'Papua New Guinea': '/countries/pg.m3u',
  'Paraguay': '/countries/py.m3u',
  'Peru': '/countries/pe.m3u',
  'Philippines': '/countries/ph.m3u',
  'Pitcairn Islands': '/countries/pn.m3u',
  'Poland': '/countries/pl.m3u',
  'Portugal': '/countries/pt.m3u',
  'Puerto Rico': '/countries/pr.m3u',
  'Qatar': '/countries/qa.m3u',
  'Romania': '/countries/ro.m3u',
  'Russia': '/countries/ru.m3u',
  'Rwanda': '/countries/rw.m3u',
  'Réunion': '/countries/re.m3u',
  'Samoa': '/countries/ws.m3u',
  'San Marino': '/countries/sm.m3u',
  'Saudi Arabia': '/countries/sa.m3u',
  'Senegal': '/countries/sn.m3u',
  'Serbia': '/countries/rs.m3u',
  'Seychelles': '/countries/sc.m3u',
  'Sierra Leone': '/countries/sl.m3u',
  'Singapore': '/countries/sg.m3u',
  'Sint Maarten': '/countries/sx.m3u',
  'Slovakia': '/countries/sk.m3u',
  'Slovenia': '/countries/si.m3u',
  'Solomon Islands': '/countries/sb.m3u',
  'Somalia': '/countries/so.m3u',
  'South Africa': '/countries/za.m3u',
  'South Korea': '/countries/kr.m3u',
  'South Sudan': '/countries/ss.m3u',
  'Spain': '/countries/es.m3u',
  'Sri Lanka': '/countries/lk.m3u',
  'St. Barthélemy': '/countries/bl.m3u',
  'St. Helena': '/countries/sh.m3u',
  'St. Kitts & Nevis': '/countries/kn.m3u',
  'St. Luci': '/countries/lc.m3u',
  'St. Martin': '/countries/mf.m3u',
  'St. Pierre & Miquelon': '/countries/pm.m3u',
  'St. Vincent & Grenadines': '/countries/vc.m3u',
  'Sudan': 'ttps://iptv-org.github.io/countries/sd.m3u',
  'Sweden': '/countries/se.m3u',
  'Switzerland': '/countries/ch.m3u',
  'Syria': '/countries/sy.m3u',
  'São Tomé & Príncipe': '/countries/st.m3u',
  'Taiwan': '/countries/tw.m3u',
  'Tajikistan': '/countries/tj.m3u',
  'Tanzania': '/countries/tz.m3u',
  'Thailand': '/countries/th.m3u',
  'Timor-Leste': '/countries/tl.m3u',
  'Togo': '/countries/tg.m3u',
  'Tokelau': '/countries/tk.m3u',
  'Tonga': '/countries/to.m3u',
  'Trinidad & Tobago': '/countries/tt.m3u',
  'Tunisia': '/countries/tn.m3u',
  'Turkey': '/countries/tr.m3u',
  'Turkmenistan': '/countries/tm.m3u',
  'Turks & Caicos Islands': '/countries/tc.m3u',
  'Tuvalu': '/countries/tv.m3u',
  'U.S. Virgin Islands': '/countries/vi.m3u',
  'Uganda': '/countries/ug.m3u',
  'Ukraine': '/countries/ua.m3u',
  'United Arab Emirates': '/countries/ae.m3u',
  'United Kingdom': '/countries/uk.m3u',
  'Uruguay': '/countries/uy.m3u',
  'Uzbekistan': '/countries/uz.m3u',
  'Vanuatu': '/countries/vu.m3u',
  'Vatican City': '/countries/va.m3u',
  'Venezuela': '/countries/ve.m3u',
  'Vietnam': '/countries/vn.m3u',
  'Wallis & Futuna': '/countries/wf.m3u',
  'Western Sahara': '/countries/eh.m3u',
  'Yemen': '/countries/ye.m3u',
  'Zambia': '/countries/zm.m3u',
  'Zimbabwe': '/countries/zw.m3u',
  'Åland Islands': '/countries/ax.m3u',
};

const LANGUAGE = {
  'Akan': '/languages/aka.m3u',
  'Albanian': '/languages/sqi.m3u',
  'Amharic': '/languages/amh.m3u',
  'Arabic': '/languages/ara.m3u',
  'Armenian': '/languages/hye.m3u',
  'Assyrian Neo-Aramaic': '/languages/aii.m3u',
  'Azerbaijani': '/languages/aze.m3u',
  'Bashkir': '/languages/bak.m3u',
  'Bengali': '/languages/ben.m3u',
  'Bosnian': '/languages/bos.m3u',
  'Bulgarian': '/languages/bul.m3u',
  'Burmese': '/languages/mya.m3u',
  'Catalan': '/languages/cat.m3u',
  'Chinese': '/languages/zho.m3u',
  'Croatian': '/languages/hrv.m3u',
  'Czech': '/languages/ces.m3u',
  'Danish': '/languages/dan.m3u',
  'Dutch': '/languages/nld.m3u',
  'Estonian': '/languages/est.m3u',
  'Faroese': '/languages/fao.m3u',
  'Finnish': '/languages/fin.m3u',
  'French': '/languages/fra.m3u',
  'Galician': '/languages/glg.m3u',
  'Georgian': '/languages/kat.m3u',
  'German': '/languages/deu.m3u',
  'Hebrew': '/languages/heb.m3u',
  'Hindi': '/languages/hin.m3u',
  'Hungarian': '/languages/hun.m3u',
  'Icelandic': '/languages/isl.m3u',
  'Indonesian': '/languages/ind.m3u',
  'Inuktitut': '/languages/iku.m3u',
  'Italian': '/languages/ita.m3u',
  'Japanese': '/languages/jpn.m3u',
  'Javanese': '/languages/jav.m3u',
  'Kannada': '/languages/kan.m3u',
  'Kazakh': '/languages/kaz.m3u',
  'Khmer': '/languages/khm.m3u',
  'Kinyarwanda': '/languages/kin.m3u',
  'Korean': '/languages/kor.m3u',
  'Kurdish': '/languages/kur.m3u',
  'Lao': '/languages/lao.m3u',
  'Latvian': '/languages/lav.m3u',
  'Lithuanian': '/languages/lit.m3u',
  'Luxembourgish': '/languages/ltz.m3u',
  'Macedonian': '/languages/mkd.m3u',
  'Malay (macrolanguage)': '/languages/msa.m3u',
  'Malayalam': '/languages/mal.m3u',
  'Maltese': '/languages/mlt.m3u',
  'Mandarin Chinese': '/languages/cmn.m3u',
  'Maori': '/languages/mri.m3u',
  'Min Nan Chinese': '/languages/nan.m3u',
  'Mongolian': '/languages/mon.m3u',
  'Montenegrin': '/languages/cnr.m3u',
  'Nepali (macrolanguage)': '/languages/nep.m3u',
  'Norwegian Bokmål': '/languages/nob.m3u',
  'Panjabi': '/languages/pan.m3u',
  'Persian': '/languages/fas.m3u',
  'Polish': '/languages/pol.m3u',
  'Portuguese': '/languages/por.m3u',
  'Pushto': '/languages/pus.m3u',
  'Romanian': '/languages/ron.m3u',
  'Russian': '/languages/rus.m3u',
  'Serbian': '/languages/srp.m3u',
  'Sinhala': '/languages/sin.m3u',
  'Slovak': '/languages/slk.m3u',
  'Slovenian': '/languages/slv.m3u',
  'Somali': '/languages/som.m3u',
  'Spanish': '/languages/spa.m3u',
  'Sundanese': '/languages/sun.m3u',
  'Swedish': '/languages/swe.m3u',
  'Tagalog': '/languages/tgl.m3u',
  'Tamil': '/languages/tam.m3u',
  'Telugu': '/languages/tel.m3u',
  'Thai': '/languages/tha.m3u',
  'Turkish': '/languages/tur.m3u',
  'Turkmen': '/languages/tuk.m3u',
  'Ukrainian': '/languages/ukr.m3u',
  'Urdu': '/languages/urd.m3u',
  'Uzbek': '/languages/uzb.m3u',
  'Vietnamese': '/languages/vie.m3u',
  'Western Frisian': '/languages/fry.m3u',
  'Yue Chinese': '/languages/yue.m3u',
}
