const BASE_URL = 'https://glcdn.githack.com/theofficialomega/backup/-/raw/main';

const CATEGORY = {
  'Auto': 'files/categories/auto.m3u',
  'Animation': 'files/categories/animation.m3u',
  'Business': 'files/categories/business.m3u',
  'Classic': 'files/categories/classic.m3u',
  'Comedy': 'files/categories/comedy.m3u',
  'Cooking': 'files/categories/cooking.m3u',
  'Culture': 'files/categories/culture.m3u',
  'Documentary': 'files/categories/documentary.m3u',
  'Education': 'files/categories/education.m3u',
  'Entertainment': 'files/categories/entertainment.m3u',
  'Family': 'files/categories/family.m3u',
  'General': 'files/categories/general.m3u',
  'Kids': 'files/categories/kids.m3u',
  'Legislative': 'files/categories/legislative.m3u',
  'Lifestyle': 'files/categories/lifestyle.m3u',
  'Local': 'files/categories/local.m3u',
  'Movies': 'files/categories/movies.m3u',
  'Music': 'files/categories/music.m3u',
  'News': 'files/categories/news.m3u',
  'Outdoor': 'files/categories/outdoor.m3u',
  'Relax': 'files/categories/relax.m3u',
  'Religious': 'files/categories/religious.m3u',
  'Series': 'files/categories/series.m3u',
  'Science': 'files/categories/science.m3u',
  'Shop': 'files/categories/shop.m3u',
  'Sports': 'files/categories/sports.m3u',
  'Travel': 'files/categories/travel.m3u',
  'Weather': 'files/categories/weather.m3u',
};

const COUNTRY = {
  'Afghanistan': 'files/countries/af.m3u',
  'Albania': 'files/countries/al.m3u',
  'Algeria': 'files/countries/dz.m3u',
  'American Samoa': 'files/countries/as.m3u',
  'Andorra': 'files/countries/ad.m3u',
  'Angola': 'files/countries/ao.m3u',
  'Anguilla': 'files/countries/ai.m3u',
  'Antigua & Barbuda': 'files/countries/ag.m3u',
  'Argentina': 'files/countries/ar.m3u',
  'Armenia': 'files/countries/am.m3u',
  'Aruba': 'files/countries/aw.m3u',
  'Australia': 'files/countries/au.m3u',
  'Austria': 'files/countries/at.m3u',
  'Azerbaijan': 'files/countries/az.m3u',
  'Bahamas': 'files/countries/bs.m3u',
  'Bahrain': 'files/countries/bh.m3u',
  'Bangladesh': 'files/countries/bd.m3u',
  'Barbados': 'files/countries/bb.m3u',
  'Belarus': 'files/countries/by.m3u',
  'Belgium': 'files/countries/be.m3u',
  'Belize': 'files/countries/bz.m3u',
  'Benin': 'files/countries/bj.m3u',
  'Bermuda': 'files/countries/bm.m3u',
  'Bhutan': 'files/countries/bt.m3u',
  'Bolivia': 'files/countries/bo.m3u',
  'Bosnia': 'files/countries/ba.m3u',
  'Botswana': 'files/countries/bw.m3u',
  'Brazil': 'files/countries/br.m3u',
  'British Virgin Islands': 'files/countries/vg.m3u',
  'Brunei': 'files/countries/bn.m3u',
  'Bulgaria': 'files/countries/bg.m3u',
  'Burkina Faso': 'files/countries/bf.m3u',
  'Burundi': 'files/countries/bi.m3u',
  'Cambodia': 'files/countries/kh.m3u',
  'Cameroon': 'files/countries/cm.m3u',
  'Canada': 'files/countries/ca.m3u',
  'Cape Verde': 'files/countries/cv.m3u',
  'Cayman Islands': 'files/countries/ky.m3u',
  'Central African Republic': 'files/countries/cf.m3u',
  'Chad': 'files/countries/td.m3u',
  'Chile': 'files/countries/cl.m3u',
  'China': 'files/countries/cn.m3u',
  'Colombia': 'files/countries/co.m3u',
  'Comoros': 'files/countries/km.m3u',
  'Congo - Brazzaville': 'files/countries/cg.m3u',
  'Congo - Kinshasa': 'files/countries/cd.m3u',
  'Cook Islands': 'files/countries/ck.m3u',
  'Costa Rica': 'files/countries/cr.m3u',
  'Croatia': 'files/countries/hr.m3u',
  'Cuba': 'files/countries/cu.m3u',
  'Curaçao': 'files/countries/cw.m3u',
  'Cyprus': 'files/countries/cy.m3u',
  'Czechia': 'files/countries/cz.m3u',
  'Côte d’Ivoire': 'files/countries/ci.m3u',
  'Denmark': 'files/countries/dk.m3u',
  'Djibouti': 'files/countries/dj.m3u',
  'Dominica': 'files/countries/dm.m3u',
  'Dominican Republic': 'files/countries/do.m3u',
  'Ecuador': 'files/countries/ec.m3u',
  'Egypt': 'files/countries/eg.m3u',
  'El Salvador': 'files/countries/sv.m3u',
  'Equatorial Guinea': 'files/countries/gq.m3u',
  'Eritrea': 'files/countries/er.m3u',
  'Estonia': 'files/countries/ee.m3u',
  'Eswatini': 'files/countries/sz.m3u',
  'Ethiopia': 'files/countries/et.m3u',
  'Faroe Islands': 'files/countries/fo.m3u',
  'Fiji': 'files/countries/fj.m3u',
  'Finland': 'files/countries/fi.m3u',
  'France': 'files/countries/fr.m3u',
  'French Guiana': 'files/countries/gf.m3u',
  'French Polynesia': 'files/countries/pf.m3u',
  'French Southern Territories': 'files/countries/tf.m3u',
  'Gabon': 'files/countries/ga.m3u',
  'Gambia': 'files/countries/gm.m3u',
  'Georgia': 'files/countries/ge.m3u',
  'Germany': 'files/countries/de.m3u',
  'Ghana': 'files/countries/gh.m3u',
  'Greece': 'files/countries/gr.m3u',
  'Greenland': 'files/countries/gl.m3u',
  'Grenada': 'files/countries/gd.m3u',
  'Guadeloupe': 'files/countries/gp.m3u',
  'Guam': 'files/countries/gu.m3u',
  'Guatemala': 'files/countries/gt.m3u',
  'Guinea': 'files/countries/gn.m3u',
  'Guinea-Bissau': 'files/countries/gw.m3u',
  'Haiti': 'files/countries/ht.m3u',
  'Honduras': 'files/countries/hn.m3u',
  'Hong Kong': 'files/countries/hk.m3u',
  'Hungary': 'files/countries/hu.m3u',
  'Iceland': 'files/countries/is.m3u',
  'India': 'files/countries/in.m3u',
  'Indonesia': 'files/countries/id.m3u',
  'International': 'files/countries/int.m3u',
  'Iran': 'files/countries/ir.m3u',
  'Iraq': 'files/countries/iq.m3u',
  'Ireland': 'files/countries/ie.m3u',
  'Israel': 'files/countries/il.m3u',
  'Italy': 'files/countries/it.m3u',
  'Jamaica': 'files/countries/jm.m3u',
  'Japan': 'files/countries/jp.m3u',
  'Jordan': 'files/countries/jo.m3u',
  'Kazakhstan': 'files/countries/kz.m3u',
  'Kenya': 'files/countries/ke.m3u',
  'Kiribati': 'files/countries/ki.m3u',
  'Kosovo': 'files/countries/xk.m3u',
  'Kuwait': 'files/countries/kw.m3u',
  'Kyrgyzstan': 'files/countries/kg.m3u',
  'Laos': 'files/countries/la.m3u',
  'Latvia': 'files/countries/lv.m3u',
  'Lebanon': 'files/countries/lb.m3u',
  'Lesotho': 'files/countries/ls.m3u',
  'Liberia': 'files/countries/lr.m3u',
  'Libya': 'files/countries/ly.m3u',
  'Liechtenstein': 'files/countries/li.m3u',
  'Lithuania': 'files/countries/lt.m3u',
  'Luxembourg': 'files/countries/lu.m3u',
  'Macao': 'files/countries/mo.m3u',
  'Madagascar': 'files/countries/mg.m3u',
  'Malawi': 'files/countries/mw.m3u',
  'Malaysia': 'files/countries/my.m3u',
  'Maldives': 'files/countries/mv.m3u',
  'Mali': 'files/countries/ml.m3u',
  'Malta': 'files/countries/mt.m3u',
  'Marshall Islands': 'files/countries/mh.m3u',
  'Martinique': 'files/countries/mq.m3u',
  'Mauritania': 'files/countries/mr.m3u',
  'Mauritius': 'files/countries/mu.m3u',
  'Mayotte': 'files/countries/yt.m3u',
  'Mexico': 'files/countries/mx.m3u',
  'Micronesia': 'files/countries/fm.m3u',
  'Moldova': 'files/countries/md.m3u',
  'Monaco': 'files/countries/mc.m3u',
  'Mongolia': 'files/countries/mn.m3u',
  'Montenegro': 'files/countries/me.m3u',
  'Montserrat': 'files/countries/ms.m3u',
  'Morocco': 'files/countries/ma.m3u',
  'Mozambique': 'files/countries/mz.m3u',
  'Myanmar': 'files/countries/mm.m3u',
  'Namibia': 'files/countries/na.m3u',
  'Nauru': 'files/countries/nr.m3u',
  'Nepal': 'files/countries/np.m3u',
  'Netherlands': 'files/countries/nl.m3u',
  'New Caledonia': 'files/countries/nc.m3u',
  'New Zealand': 'files/countries/nz.m3u',
  'Nicaragua': 'files/countries/ni.m3u',
  'Niger': 'files/countries/ne.m3u',
  'Nigeria': 'files/countries/ng.m3u',
  'Niue': 'files/countries/nu.m3u',
  'Norfolk Island': 'files/countries/nf.m3u',
  'North Korea': 'files/countries/kp.m3u',
  'North Macedonia': 'files/countries/mk.m3u',
  'Northern Mariana Islands': 'files/countries/mp.m3u',
  'Norway': 'files/countries/no.m3u',
  'Oman': 'files/countries/om.m3u',
  'Pakistan': 'files/countries/pk.m3u',
  'Palau': 'files/countries/pw.m3u',
  'Palestine': 'files/countries/ps.m3u',
  'Panama': 'files/countries/pa.m3u',
  'Papua New Guinea': 'files/countries/pg.m3u',
  'Paraguay': 'files/countries/py.m3u',
  'Peru': 'files/countries/pe.m3u',
  'Philippines': 'files/countries/ph.m3u',
  'Pitcairn Islands': 'files/countries/pn.m3u',
  'Poland': 'files/countries/pl.m3u',
  'Portugal': 'files/countries/pt.m3u',
  'Puerto Rico': 'files/countries/pr.m3u',
  'Qatar': 'files/countries/qa.m3u',
  'Romania': 'files/countries/ro.m3u',
  'Russia': 'files/countries/ru.m3u',
  'Rwanda': 'files/countries/rw.m3u',
  'Réunion': 'files/countries/re.m3u',
  'Samoa': 'files/countries/ws.m3u',
  'San Marino': 'files/countries/sm.m3u',
  'Saudi Arabia': 'files/countries/sa.m3u',
  'Senegal': 'files/countries/sn.m3u',
  'Serbia': 'files/countries/rs.m3u',
  'Seychelles': 'files/countries/sc.m3u',
  'Sierra Leone': 'files/countries/sl.m3u',
  'Singapore': 'files/countries/sg.m3u',
  'Sint Maarten': 'files/countries/sx.m3u',
  'Slovakia': 'files/countries/sk.m3u',
  'Slovenia': 'files/countries/si.m3u',
  'Solomon Islands': 'files/countries/sb.m3u',
  'Somalia': 'files/countries/so.m3u',
  'South Africa': 'files/countries/za.m3u',
  'South Korea': 'files/countries/kr.m3u',
  'South Sudan': 'files/countries/ss.m3u',
  'Spain': 'files/countries/es.m3u',
  'Sri Lanka': 'files/countries/lk.m3u',
  'St. Barthélemy': 'files/countries/bl.m3u',
  'St. Helena': 'files/countries/sh.m3u',
  'St. Kitts & Nevis': 'files/countries/kn.m3u',
  'St. Luci': 'files/countries/lc.m3u',
  'St. Martin': 'files/countries/mf.m3u',
  'St. Pierre & Miquelon': 'files/countries/pm.m3u',
  'St. Vincent & Grenadines': 'files/countries/vc.m3u',
  'Sudan': 'ttps://iptv-org.github.iofiles/countries/sd.m3u',
  'Sweden': 'files/countries/se.m3u',
  'Switzerland': 'files/countries/ch.m3u',
  'Syria': 'files/countries/sy.m3u',
  'São Tomé & Príncipe': 'files/countries/st.m3u',
  'Taiwan': 'files/countries/tw.m3u',
  'Tajikistan': 'files/countries/tj.m3u',
  'Tanzania': 'files/countries/tz.m3u',
  'Thailand': 'files/countries/th.m3u',
  'Timor-Leste': 'files/countries/tl.m3u',
  'Togo': 'files/countries/tg.m3u',
  'Tokelau': 'files/countries/tk.m3u',
  'Tonga': 'files/countries/to.m3u',
  'Trinidad & Tobago': 'files/countries/tt.m3u',
  'Tunisia': 'files/countries/tn.m3u',
  'Turkey': 'files/countries/tr.m3u',
  'Turkmenistan': 'files/countries/tm.m3u',
  'Turks & Caicos Islands': 'files/countries/tc.m3u',
  'Tuvalu': 'files/countries/tv.m3u',
  'U.S. Virgin Islands': 'files/countries/vi.m3u',
  'Uganda': 'files/countries/ug.m3u',
  'Ukraine': 'files/countries/ua.m3u',
  'United Arab Emirates': 'files/countries/ae.m3u',
  'United Kingdom': 'files/countries/uk.m3u',
  'Uruguay': 'files/countries/uy.m3u',
  'Uzbekistan': 'files/countries/uz.m3u',
  'Vanuatu': 'files/countries/vu.m3u',
  'Vatican City': 'files/countries/va.m3u',
  'Venezuela': 'files/countries/ve.m3u',
  'Vietnam': 'files/countries/vn.m3u',
  'Wallis & Futuna': 'files/countries/wf.m3u',
  'Western Sahara': 'files/countries/eh.m3u',
  'Yemen': 'files/countries/ye.m3u',
  'Zambia': 'files/countries/zm.m3u',
  'Zimbabwe': 'files/countries/zw.m3u',
  'Åland Islands': 'files/countries/ax.m3u',
};

const LANGUAGE = {
  'Akan': 'files/languages/aka.m3u',
  'Albanian': 'files/languages/sqi.m3u',
  'Amharic': 'files/languages/amh.m3u',
  'Arabic': 'files/languages/ara.m3u',
  'Armenian': 'files/languages/hye.m3u',
  'Assyrian Neo-Aramaic': 'files/languages/aii.m3u',
  'Azerbaijani': 'files/languages/aze.m3u',
  'Bashkir': 'files/languages/bak.m3u',
  'Bengali': 'files/languages/ben.m3u',
  'Bosnian': 'files/languages/bos.m3u',
  'Bulgarian': 'files/languages/bul.m3u',
  'Burmese': 'files/languages/mya.m3u',
  'Catalan': 'files/languages/cat.m3u',
  'Chinese': 'files/languages/zho.m3u',
  'Croatian': 'files/languages/hrv.m3u',
  'Czech': 'files/languages/ces.m3u',
  'Danish': 'files/languages/dan.m3u',
  'Dutch': 'files/languages/nld.m3u',
  'Estonian': 'files/languages/est.m3u',
  'Faroese': 'files/languages/fao.m3u',
  'Finnish': 'files/languages/fin.m3u',
  'French': 'files/languages/fra.m3u',
  'Galician': 'files/languages/glg.m3u',
  'Georgian': 'files/languages/kat.m3u',
  'German': 'files/languages/deu.m3u',
  'Hebrew': 'files/languages/heb.m3u',
  'Hindi': 'files/languages/hin.m3u',
  'Hungarian': 'files/languages/hun.m3u',
  'Icelandic': 'files/languages/isl.m3u',
  'Indonesian': 'files/languages/ind.m3u',
  'Inuktitut': 'files/languages/iku.m3u',
  'Italian': 'files/languages/ita.m3u',
  'Japanese': 'files/languages/jpn.m3u',
  'Javanese': 'files/languages/jav.m3u',
  'Kannada': 'files/languages/kan.m3u',
  'Kazakh': 'files/languages/kaz.m3u',
  'Khmer': 'files/languages/khm.m3u',
  'Kinyarwanda': 'files/languages/kin.m3u',
  'Korean': 'files/languages/kor.m3u',
  'Kurdish': 'files/languages/kur.m3u',
  'Lao': 'files/languages/lao.m3u',
  'Latvian': 'files/languages/lav.m3u',
  'Lithuanian': 'files/languages/lit.m3u',
  'Luxembourgish': 'files/languages/ltz.m3u',
  'Macedonian': 'files/languages/mkd.m3u',
  'Malay (macrolanguage)': 'files/languages/msa.m3u',
  'Malayalam': 'files/languages/mal.m3u',
  'Maltese': 'files/languages/mlt.m3u',
  'Mandarin Chinese': 'files/languages/cmn.m3u',
  'Maori': 'files/languages/mri.m3u',
  'Min Nan Chinese': 'files/languages/nan.m3u',
  'Mongolian': 'files/languages/mon.m3u',
  'Montenegrin': 'files/languages/cnr.m3u',
  'Nepali (macrolanguage)': 'files/languages/nep.m3u',
  'Norwegian Bokmål': 'files/languages/nob.m3u',
  'Panjabi': 'files/languages/pan.m3u',
  'Persian': 'files/languages/fas.m3u',
  'Polish': 'files/languages/pol.m3u',
  'Portuguese': 'files/languages/por.m3u',
  'Pushto': 'files/languages/pus.m3u',
  'Romanian': 'files/languages/ron.m3u',
  'Russian': 'files/languages/rus.m3u',
  'Serbian': 'files/languages/srp.m3u',
  'Sinhala': 'files/languages/sin.m3u',
  'Slovak': 'files/languages/slk.m3u',
  'Slovenian': 'files/languages/slv.m3u',
  'Somali': 'files/languages/som.m3u',
  'Spanish': 'files/languages/spa.m3u',
  'Sundanese': 'files/languages/sun.m3u',
  'Swedish': 'files/languages/swe.m3u',
  'Tagalog': 'files/languages/tgl.m3u',
  'Tamil': 'files/languages/tam.m3u',
  'Telugu': 'files/languages/tel.m3u',
  'Thai': 'files/languages/tha.m3u',
  'Turkish': 'files/languages/tur.m3u',
  'Turkmen': 'files/languages/tuk.m3u',
  'Ukrainian': 'files/languages/ukr.m3u',
  'Urdu': 'files/languages/urd.m3u',
  'Uzbek': 'files/languages/uzb.m3u',
  'Vietnamese': 'files/languages/vie.m3u',
  'Western Frisian': 'files/languages/fry.m3u',
  'Yue Chinese': 'files/languages/yue.m3u',
}
