const BASE_URL = 'https://iptv-org.github.io';

const CATEGORY = {
  'Auto': 'iptv/categories/auto.m3u',
  'Animation': 'iptv/categories/animation.m3u',
  'Business': 'iptv/categories/business.m3u',
  'Classic': 'iptv/categories/classic.m3u',
  'Comedy': 'iptv/categories/comedy.m3u',
  'Cooking': 'iptv/categories/cooking.m3u',
  'Culture': 'iptv/categories/culture.m3u',
  'Documentary': 'iptv/categories/documentary.m3u',
  'Education': 'iptv/categories/education.m3u',
  'Entertainment': 'iptv/categories/entertainment.m3u',
  'Family': 'iptv/categories/family.m3u',
  'General': 'iptv/categories/general.m3u',
  'Kids': 'iptv/categories/kids.m3u',
  'Legislative': 'iptv/categories/legislative.m3u',
  'Lifestyle': 'iptv/categories/lifestyle.m3u',
  'Local': 'iptv/categories/local.m3u',
  'Movies': 'iptv/categories/movies.m3u',
  'Music': 'iptv/categories/music.m3u',
  'News': 'iptv/categories/news.m3u',
  'Outdoor': 'iptv/categories/outdoor.m3u',
  'Relax': 'iptv/categories/relax.m3u',
  'Religious': 'iptv/categories/religious.m3u',
  'Series': 'iptv/categories/series.m3u',
  'Science': 'iptv/categories/science.m3u',
  'Shop': 'iptv/categories/shop.m3u',
  'Sports': 'iptv/categories/sports.m3u',
  'Travel': 'iptv/categories/travel.m3u',
  'Weather': 'iptv/categories/weather.m3u',
};

const COUNTRY = {
  'Afghanistan': 'iptv/countries/af.m3u',
  'Albania': 'iptv/countries/al.m3u',
  'Algeria': 'iptv/countries/dz.m3u',
  'American Samoa': 'iptv/countries/as.m3u',
  'Andorra': 'iptv/countries/ad.m3u',
  'Angola': 'iptv/countries/ao.m3u',
  'Anguilla': 'iptv/countries/ai.m3u',
  'Antigua & Barbuda': 'iptv/countries/ag.m3u',
  'Argentina': 'iptv/countries/ar.m3u',
  'Armenia': 'iptv/countries/am.m3u',
  'Aruba': 'iptv/countries/aw.m3u',
  'Australia': 'iptv/countries/au.m3u',
  'Austria': 'iptv/countries/at.m3u',
  'Azerbaijan': 'iptv/countries/az.m3u',
  'Bahamas': 'iptv/countries/bs.m3u',
  'Bahrain': 'iptv/countries/bh.m3u',
  'Bangladesh': 'iptv/countries/bd.m3u',
  'Barbados': 'iptv/countries/bb.m3u',
  'Belarus': 'iptv/countries/by.m3u',
  'Belgium': 'iptv/countries/be.m3u',
  'Belize': 'iptv/countries/bz.m3u',
  'Benin': 'iptv/countries/bj.m3u',
  'Bermuda': 'iptv/countries/bm.m3u',
  'Bhutan': 'iptv/countries/bt.m3u',
  'Bolivia': 'iptv/countries/bo.m3u',
  'Bosnia': 'iptv/countries/ba.m3u',
  'Botswana': 'iptv/countries/bw.m3u',
  'Brazil': 'iptv/countries/br.m3u',
  'British Virgin Islands': 'iptv/countries/vg.m3u',
  'Brunei': 'iptv/countries/bn.m3u',
  'Bulgaria': 'iptv/countries/bg.m3u',
  'Burkina Faso': 'iptv/countries/bf.m3u',
  'Burundi': 'iptv/countries/bi.m3u',
  'Cambodia': 'iptv/countries/kh.m3u',
  'Cameroon': 'iptv/countries/cm.m3u',
  'Canada': 'iptv/countries/ca.m3u',
  'Cape Verde': 'iptv/countries/cv.m3u',
  'Cayman Islands': 'iptv/countries/ky.m3u',
  'Central African Republic': 'iptv/countries/cf.m3u',
  'Chad': 'iptv/countries/td.m3u',
  'Chile': 'iptv/countries/cl.m3u',
  'China': 'iptv/countries/cn.m3u',
  'Colombia': 'iptv/countries/co.m3u',
  'Comoros': 'iptv/countries/km.m3u',
  'Congo - Brazzaville': 'iptv/countries/cg.m3u',
  'Congo - Kinshasa': 'iptv/countries/cd.m3u',
  'Cook Islands': 'iptv/countries/ck.m3u',
  'Costa Rica': 'iptv/countries/cr.m3u',
  'Croatia': 'iptv/countries/hr.m3u',
  'Cuba': 'iptv/countries/cu.m3u',
  'Curaçao': 'iptv/countries/cw.m3u',
  'Cyprus': 'iptv/countries/cy.m3u',
  'Czechia': 'iptv/countries/cz.m3u',
  'Côte d’Ivoire': 'iptv/countries/ci.m3u',
  'Denmark': 'iptv/countries/dk.m3u',
  'Djibouti': 'iptv/countries/dj.m3u',
  'Dominica': 'iptv/countries/dm.m3u',
  'Dominican Republic': 'iptv/countries/do.m3u',
  'Ecuador': 'iptv/countries/ec.m3u',
  'Egypt': 'iptv/countries/eg.m3u',
  'El Salvador': 'iptv/countries/sv.m3u',
  'Equatorial Guinea': 'iptv/countries/gq.m3u',
  'Eritrea': 'iptv/countries/er.m3u',
  'Estonia': 'iptv/countries/ee.m3u',
  'Eswatini': 'iptv/countries/sz.m3u',
  'Ethiopia': 'iptv/countries/et.m3u',
  'Faroe Islands': 'iptv/countries/fo.m3u',
  'Fiji': 'iptv/countries/fj.m3u',
  'Finland': 'iptv/countries/fi.m3u',
  'France': 'iptv/countries/fr.m3u',
  'French Guiana': 'iptv/countries/gf.m3u',
  'French Polynesia': 'iptv/countries/pf.m3u',
  'French Southern Territories': 'iptv/countries/tf.m3u',
  'Gabon': 'iptv/countries/ga.m3u',
  'Gambia': 'iptv/countries/gm.m3u',
  'Georgia': 'iptv/countries/ge.m3u',
  'Germany': 'iptv/countries/de.m3u',
  'Ghana': 'iptv/countries/gh.m3u',
  'Greece': 'iptv/countries/gr.m3u',
  'Greenland': 'iptv/countries/gl.m3u',
  'Grenada': 'iptv/countries/gd.m3u',
  'Guadeloupe': 'iptv/countries/gp.m3u',
  'Guam': 'iptv/countries/gu.m3u',
  'Guatemala': 'iptv/countries/gt.m3u',
  'Guinea': 'iptv/countries/gn.m3u',
  'Guinea-Bissau': 'iptv/countries/gw.m3u',
  'Haiti': 'iptv/countries/ht.m3u',
  'Honduras': 'iptv/countries/hn.m3u',
  'Hong Kong': 'iptv/countries/hk.m3u',
  'Hungary': 'iptv/countries/hu.m3u',
  'Iceland': 'iptv/countries/is.m3u',
  'India': 'iptv/countries/in.m3u',
  'Indonesia': 'iptv/countries/id.m3u',
  'International': 'iptv/countries/int.m3u',
  'Iran': 'iptv/countries/ir.m3u',
  'Iraq': 'iptv/countries/iq.m3u',
  'Ireland': 'iptv/countries/ie.m3u',
  'Israel': 'iptv/countries/il.m3u',
  'Italy': 'iptv/countries/it.m3u',
  'Jamaica': 'iptv/countries/jm.m3u',
  'Japan': 'iptv/countries/jp.m3u',
  'Jordan': 'iptv/countries/jo.m3u',
  'Kazakhstan': 'iptv/countries/kz.m3u',
  'Kenya': 'iptv/countries/ke.m3u',
  'Kiribati': 'iptv/countries/ki.m3u',
  'Kosovo': 'iptv/countries/xk.m3u',
  'Kuwait': 'iptv/countries/kw.m3u',
  'Kyrgyzstan': 'iptv/countries/kg.m3u',
  'Laos': 'iptv/countries/la.m3u',
  'Latvia': 'iptv/countries/lv.m3u',
  'Lebanon': 'iptv/countries/lb.m3u',
  'Lesotho': 'iptv/countries/ls.m3u',
  'Liberia': 'iptv/countries/lr.m3u',
  'Libya': 'iptv/countries/ly.m3u',
  'Liechtenstein': 'iptv/countries/li.m3u',
  'Lithuania': 'iptv/countries/lt.m3u',
  'Luxembourg': 'iptv/countries/lu.m3u',
  'Macao': 'iptv/countries/mo.m3u',
  'Madagascar': 'iptv/countries/mg.m3u',
  'Malawi': 'iptv/countries/mw.m3u',
  'Malaysia': 'iptv/countries/my.m3u',
  'Maldives': 'iptv/countries/mv.m3u',
  'Mali': 'iptv/countries/ml.m3u',
  'Malta': 'iptv/countries/mt.m3u',
  'Marshall Islands': 'iptv/countries/mh.m3u',
  'Martinique': 'iptv/countries/mq.m3u',
  'Mauritania': 'iptv/countries/mr.m3u',
  'Mauritius': 'iptv/countries/mu.m3u',
  'Mayotte': 'iptv/countries/yt.m3u',
  'Mexico': 'iptv/countries/mx.m3u',
  'Micronesia': 'iptv/countries/fm.m3u',
  'Moldova': 'iptv/countries/md.m3u',
  'Monaco': 'iptv/countries/mc.m3u',
  'Mongolia': 'iptv/countries/mn.m3u',
  'Montenegro': 'iptv/countries/me.m3u',
  'Montserrat': 'iptv/countries/ms.m3u',
  'Morocco': 'iptv/countries/ma.m3u',
  'Mozambique': 'iptv/countries/mz.m3u',
  'Myanmar': 'iptv/countries/mm.m3u',
  'Namibia': 'iptv/countries/na.m3u',
  'Nauru': 'iptv/countries/nr.m3u',
  'Nepal': 'iptv/countries/np.m3u',
  'Netherlands': 'iptv/countries/nl.m3u',
  'New Caledonia': 'iptv/countries/nc.m3u',
  'New Zealand': 'iptv/countries/nz.m3u',
  'Nicaragua': 'iptv/countries/ni.m3u',
  'Niger': 'iptv/countries/ne.m3u',
  'Nigeria': 'iptv/countries/ng.m3u',
  'Niue': 'iptv/countries/nu.m3u',
  'Norfolk Island': 'iptv/countries/nf.m3u',
  'North Korea': 'iptv/countries/kp.m3u',
  'North Macedonia': 'iptv/countries/mk.m3u',
  'Northern Mariana Islands': 'iptv/countries/mp.m3u',
  'Norway': 'iptv/countries/no.m3u',
  'Oman': 'iptv/countries/om.m3u',
  'Pakistan': 'iptv/countries/pk.m3u',
  'Palau': 'iptv/countries/pw.m3u',
  'Palestine': 'iptv/countries/ps.m3u',
  'Panama': 'iptv/countries/pa.m3u',
  'Papua New Guinea': 'iptv/countries/pg.m3u',
  'Paraguay': 'iptv/countries/py.m3u',
  'Peru': 'iptv/countries/pe.m3u',
  'Philippines': 'iptv/countries/ph.m3u',
  'Pitcairn Islands': 'iptv/countries/pn.m3u',
  'Poland': 'iptv/countries/pl.m3u',
  'Portugal': 'iptv/countries/pt.m3u',
  'Puerto Rico': 'iptv/countries/pr.m3u',
  'Qatar': 'iptv/countries/qa.m3u',
  'Romania': 'iptv/countries/ro.m3u',
  'Russia': 'iptv/countries/ru.m3u',
  'Rwanda': 'iptv/countries/rw.m3u',
  'Réunion': 'iptv/countries/re.m3u',
  'Samoa': 'iptv/countries/ws.m3u',
  'San Marino': 'iptv/countries/sm.m3u',
  'Saudi Arabia': 'iptv/countries/sa.m3u',
  'Senegal': 'iptv/countries/sn.m3u',
  'Serbia': 'iptv/countries/rs.m3u',
  'Seychelles': 'iptv/countries/sc.m3u',
  'Sierra Leone': 'iptv/countries/sl.m3u',
  'Singapore': 'iptv/countries/sg.m3u',
  'Sint Maarten': 'iptv/countries/sx.m3u',
  'Slovakia': 'iptv/countries/sk.m3u',
  'Slovenia': 'iptv/countries/si.m3u',
  'Solomon Islands': 'iptv/countries/sb.m3u',
  'Somalia': 'iptv/countries/so.m3u',
  'South Africa': 'iptv/countries/za.m3u',
  'South Korea': 'iptv/countries/kr.m3u',
  'South Sudan': 'iptv/countries/ss.m3u',
  'Spain': 'iptv/countries/es.m3u',
  'Sri Lanka': 'iptv/countries/lk.m3u',
  'St. Barthélemy': 'iptv/countries/bl.m3u',
  'St. Helena': 'iptv/countries/sh.m3u',
  'St. Kitts & Nevis': 'iptv/countries/kn.m3u',
  'St. Luci': 'iptv/countries/lc.m3u',
  'St. Martin': 'iptv/countries/mf.m3u',
  'St. Pierre & Miquelon': 'iptv/countries/pm.m3u',
  'St. Vincent & Grenadines': 'iptv/countries/vc.m3u',
  'Sudan': 'ttps://iptv-org.github.ioiptv/countries/sd.m3u',
  'Sweden': 'iptv/countries/se.m3u',
  'Switzerland': 'iptv/countries/ch.m3u',
  'Syria': 'iptv/countries/sy.m3u',
  'São Tomé & Príncipe': 'iptv/countries/st.m3u',
  'Taiwan': 'iptv/countries/tw.m3u',
  'Tajikistan': 'iptv/countries/tj.m3u',
  'Tanzania': 'iptv/countries/tz.m3u',
  'Thailand': 'iptv/countries/th.m3u',
  'Timor-Leste': 'iptv/countries/tl.m3u',
  'Togo': 'iptv/countries/tg.m3u',
  'Tokelau': 'iptv/countries/tk.m3u',
  'Tonga': 'iptv/countries/to.m3u',
  'Trinidad & Tobago': 'iptv/countries/tt.m3u',
  'Tunisia': 'iptv/countries/tn.m3u',
  'Turkey': 'iptv/countries/tr.m3u',
  'Turkmenistan': 'iptv/countries/tm.m3u',
  'Turks & Caicos Islands': 'iptv/countries/tc.m3u',
  'Tuvalu': 'iptv/countries/tv.m3u',
  'U.S. Virgin Islands': 'iptv/countries/vi.m3u',
  'Uganda': 'iptv/countries/ug.m3u',
  'Ukraine': 'iptv/countries/ua.m3u',
  'United Arab Emirates': 'iptv/countries/ae.m3u',
  'United Kingdom': 'iptv/countries/uk.m3u',
  'Uruguay': 'iptv/countries/uy.m3u',
  'Uzbekistan': 'iptv/countries/uz.m3u',
  'Vanuatu': 'iptv/countries/vu.m3u',
  'Vatican City': 'iptv/countries/va.m3u',
  'Venezuela': 'iptv/countries/ve.m3u',
  'Vietnam': 'iptv/countries/vn.m3u',
  'Wallis & Futuna': 'iptv/countries/wf.m3u',
  'Western Sahara': 'iptv/countries/eh.m3u',
  'Yemen': 'iptv/countries/ye.m3u',
  'Zambia': 'iptv/countries/zm.m3u',
  'Zimbabwe': 'iptv/countries/zw.m3u',
  'Åland Islands': 'iptv/countries/ax.m3u',
};

const LANGUAGE = {
  'Akan': 'iptv/languages/aka.m3u',
  'Albanian': 'iptv/languages/sqi.m3u',
  'Amharic': 'iptv/languages/amh.m3u',
  'Arabic': 'iptv/languages/ara.m3u',
  'Armenian': 'iptv/languages/hye.m3u',
  'Assyrian Neo-Aramaic': 'iptv/languages/aii.m3u',
  'Azerbaijani': 'iptv/languages/aze.m3u',
  'Bashkir': 'iptv/languages/bak.m3u',
  'Bengali': 'iptv/languages/ben.m3u',
  'Bosnian': 'iptv/languages/bos.m3u',
  'Bulgarian': 'iptv/languages/bul.m3u',
  'Burmese': 'iptv/languages/mya.m3u',
  'Catalan': 'iptv/languages/cat.m3u',
  'Chinese': 'iptv/languages/zho.m3u',
  'Croatian': 'iptv/languages/hrv.m3u',
  'Czech': 'iptv/languages/ces.m3u',
  'Danish': 'iptv/languages/dan.m3u',
  'Dutch': 'iptv/languages/nld.m3u',
  'Estonian': 'iptv/languages/est.m3u',
  'Faroese': 'iptv/languages/fao.m3u',
  'Finnish': 'iptv/languages/fin.m3u',
  'French': 'iptv/languages/fra.m3u',
  'Galician': 'iptv/languages/glg.m3u',
  'Georgian': 'iptv/languages/kat.m3u',
  'German': 'iptv/languages/deu.m3u',
  'Hebrew': 'iptv/languages/heb.m3u',
  'Hindi': 'iptv/languages/hin.m3u',
  'Hungarian': 'iptv/languages/hun.m3u',
  'Icelandic': 'iptv/languages/isl.m3u',
  'Indonesian': 'iptv/languages/ind.m3u',
  'Inuktitut': 'iptv/languages/iku.m3u',
  'Italian': 'iptv/languages/ita.m3u',
  'Japanese': 'iptv/languages/jpn.m3u',
  'Javanese': 'iptv/languages/jav.m3u',
  'Kannada': 'iptv/languages/kan.m3u',
  'Kazakh': 'iptv/languages/kaz.m3u',
  'Khmer': 'iptv/languages/khm.m3u',
  'Kinyarwanda': 'iptv/languages/kin.m3u',
  'Korean': 'iptv/languages/kor.m3u',
  'Kurdish': 'iptv/languages/kur.m3u',
  'Lao': 'iptv/languages/lao.m3u',
  'Latvian': 'iptv/languages/lav.m3u',
  'Lithuanian': 'iptv/languages/lit.m3u',
  'Luxembourgish': 'iptv/languages/ltz.m3u',
  'Macedonian': 'iptv/languages/mkd.m3u',
  'Malay (macrolanguage)': 'iptv/languages/msa.m3u',
  'Malayalam': 'iptv/languages/mal.m3u',
  'Maltese': 'iptv/languages/mlt.m3u',
  'Mandarin Chinese': 'iptv/languages/cmn.m3u',
  'Maori': 'iptv/languages/mri.m3u',
  'Min Nan Chinese': 'iptv/languages/nan.m3u',
  'Mongolian': 'iptv/languages/mon.m3u',
  'Montenegrin': 'iptv/languages/cnr.m3u',
  'Nepali (macrolanguage)': 'iptv/languages/nep.m3u',
  'Norwegian Bokmål': 'iptv/languages/nob.m3u',
  'Panjabi': 'iptv/languages/pan.m3u',
  'Persian': 'iptv/languages/fas.m3u',
  'Polish': 'iptv/languages/pol.m3u',
  'Portuguese': 'iptv/languages/por.m3u',
  'Pushto': 'iptv/languages/pus.m3u',
  'Romanian': 'iptv/languages/ron.m3u',
  'Russian': 'iptv/languages/rus.m3u',
  'Serbian': 'iptv/languages/srp.m3u',
  'Sinhala': 'iptv/languages/sin.m3u',
  'Slovak': 'iptv/languages/slk.m3u',
  'Slovenian': 'iptv/languages/slv.m3u',
  'Somali': 'iptv/languages/som.m3u',
  'Spanish': 'iptv/languages/spa.m3u',
  'Sundanese': 'iptv/languages/sun.m3u',
  'Swedish': 'iptv/languages/swe.m3u',
  'Tagalog': 'iptv/languages/tgl.m3u',
  'Tamil': 'iptv/languages/tam.m3u',
  'Telugu': 'iptv/languages/tel.m3u',
  'Thai': 'iptv/languages/tha.m3u',
  'Turkish': 'iptv/languages/tur.m3u',
  'Turkmen': 'iptv/languages/tuk.m3u',
  'Ukrainian': 'iptv/languages/ukr.m3u',
  'Urdu': 'iptv/languages/urd.m3u',
  'Uzbek': 'iptv/languages/uzb.m3u',
  'Vietnamese': 'iptv/languages/vie.m3u',
  'Western Frisian': 'iptv/languages/fry.m3u',
  'Yue Chinese': 'iptv/languages/yue.m3u',
}
